repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: check-added-large-files
  - id: check-docstring-first
  - id: debug-statements
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-ast
  - id: check-builtin-literals
  - id: detect-private-key
  - id: mixed-line-ending
-   repo: local
    hooks:
      - id: bandit
        name: 🎰 Checking using bandit
        language: system
        types: [python]
        entry: uv run bandit
        files: ^tesla_wall_connector/
        require_serial: true
      - id: ruff-check
        name: 🪶 Lint using ruff
        language: system
        types: [python]
        entry: uv run ruff check --fix
        require_serial: true
      - id: ruff-format
        name: ✨ Format using ruff
        language: system
        types: [python]
        entry: uv run ruff format
        require_serial: true
      - id: codespell
        name: ✅ Check code for common misspellings
        language: system
        types: [text]
        exclude: ^uv\.lock$
        entry: uv run codespell
      - id: uv-lock
        name: 📜 Check lockfile with uv
        language: system
        entry: uv lock --check
        pass_filenames: false
        always_run: true
      - id: pyright
        name: 📐 Type check with pyright
        language: system
        types: [python]
        entry: uv run pyright
        pass_filenames: false
      - id: pytest
        name: 🧪 Running tests and test coverage with pytest
        language: system
        types: [python]
        entry: uv run pytest
        pass_filenames: false
