[tool.poetry]
name = "tesla-wall-connector"
version = "0.1.0"
description = "API Library for communicating with a Tesla Wall Connector"
authors = ["Einar Bragi Hauksson"]

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = "^3.7.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
