[tool.poetry]
name = "tesla-wall-connector"
version = "0.1.0"
description = "API Library for communicating with a Tesla Wall Connector"
authors = ["Einar Bragi Hauksson"]

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = "^3.7.4"
pytest = "^6.2.5"
backoff = "^1.11.1"

[tool.poetry.dev-dependencies]
aresponses = "^2.1.4"
pytest-asyncio = "^0.15.1"
black = "^21.9b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
